### ISSUE TITLE
Question, protobuf version

### ISSUE THREAD

**Issue by damianoneill** [NathanBaulch/protoc-gen-cobra#3]
Hi @NathanBaulch, thanks for the tool. 

I was wondering if there was any way that the client connecting to the server could confirm that the proto used to generate the client was the same as the proto used on the server-side?

Thanks,
Damian.

**Comment by damianoneill** [comment]
Hi Nathan was wondering if you had a chance to think about the question above?

Thanks,
Damian.

**Comment by NathanBaulch** [comment]
Sorry Damian, I'm not aware of any protobuf feature that would allow for this, at least not built into the protocol. I'm no expert but the wire format is very minimal and the documentation puts a strong emphasis on maintaining backward compatibility as your server APIs evolve so that mismatched clients and servers have a good chance of working together.

I haven't used it myself but there is the optional [server reflection](`https://github.com/grpc/grpc/blob/master/doc/server-reflection.md`) protocol which might help. In theory you could generate a Cobra CLI to explore those APIs on any server that supports it.

**Comment by damianoneill** [comment]
Thanks Nathan, appreciate the response.
